apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-app
  namespace: pipeline-local
  labels:
    app: math-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: math-app
  template:
    metadata:
      labels:
        app: math-app
    spec:
      containers:
      - name: math-app
        image: docker.io/${DOCKERHUB_USERNAME}/pipeline:${IMAGE_TAG}
        imagePullPolicy: Always
        command: ["python", "my_math.py"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline-local